name: Test

on:
  push:
  workflow_dispatch:

defaults:
  run:
    shell: bash

env:
  lldb_release: codelldb/22.x-72
  rust_version: 1.91.0
  version_suffix: ${{ inputs.final && ' ' || '-' }}
  SCCACHE_GHA_ENABLED: true

jobs:
  build:
    permissions:
      actions: read
      contents: read

    strategy:
      fail-fast: false
      matrix:
        include:
        - os: Windows
          image: windows-latest
          lldb_triple: x86_64-windows-msvc
          rust_toolchain: x86_64-pc-windows-gnu
          rust_targets: x86_64-pc-windows-msvc
          platformid: win32-x64
          vcvars: vcvars64

        - os: Windows
          image: windows-11-vs2026-arm
          lldb_triple: aarch64-windows-msvc
          rust_toolchain: aarch64-pc-windows-msvc
          rust_targets: aarch64-pc-windows-msvc
          platformid: win32-arm64
          vcvars: vcvarsarm64

    name: ${{ matrix.os }} ${{ matrix.platformid }}
    runs-on: ${{ matrix.image }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup (Windows)
      shell: cmd
      run: |
        call "C:\Program Files\Microsoft Visual Studio\18\Enterprise\VC\Auxiliary\Build\${{ matrix.vcvars }}.bat" || call "C:\Program Files (x86)\Microsoft Visual Studio\18\Enterprise\VC\Auxiliary\Build\${{ matrix.vcvars }}.bat"
        set >> %GITHUB_ENV%
        which link.exe

    - name: Which in bash
      run: |
        which link.exe

    - name: Which in cmd again
      shell: cmd
      run: |
        which link.exe

    - name: Rust build
      run: |
        cargo build
